# Copyright 2026 koyan9
# SPDX-License-Identifier: Apache-2.0

spring:
  datasource:
    url: jdbc:h2:file:./target/privacy-demo-custom-jdbc-tenant-shared;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

demo:
  instance-id: custom-jdbc-node-1

privacy:
  guard:
    audit:
      repository-type: JDBC
      jdbc:
        initialize-schema: true
        dialect: H2
        table-name: privacy_audit_event_custom_jdbc_demo
        tenant-column-name: tenant_key
        tenant-detail-key: tenant
      dead-letter:
        repository-type: JDBC
        jdbc:
          initialize-schema: true
          dialect: H2
          table-name: privacy_audit_dead_letter_custom_jdbc_demo
          tenant-column-name: tenant_key
          tenant-detail-key: tenant
        observability:
          alert:
            receiver:
              replay-store:
                jdbc:
                  enabled: true
                  initialize-schema: true
                  dialect: H2
                  table-name: privacy_audit_webhook_replay_store_custom_jdbc_demo
                  cleanup-interval: 5m
